backend:
  name: github
  repo: rayyyy/blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    fields:
      - { name: slug, label: slug }
      - { name: published_date, label: 投稿日, widget: date }
      - { name: updated_date, label: 更新日時, widget: date }
      - { name: title, label: 記事タイトル }
      - { name: body, label: 本文, widget: markdown }
      - { name: tags, label: タグ, widget: list }